-- drop all tables in reverse order of their dependencies
DROP TABLE IF EXISTS DBO.ACCOUNT_BALANCE;
GO

DROP TABLE IF EXISTS DBO.REWARDS_ACTIVITY;
GO

DROP TABLE IF EXISTS DBO.REWARDS_TRANSACTION_ITEM;
GO

DROP TABLE IF EXISTS DBO.ITEM;
GO

DROP TABLE IF EXISTS DBO.REWARDS_TRANSACTION;
GO

DROP TABLE IF EXISTS DBO.TRANSACTIONN;
GO

DROP TABLE IF EXISTS DBO.ACCOUNT_USERS;
GO

DROP TABLE IF EXISTS DBO.ACCOUNT_XREFERENCE;
GO

DROP TABLE IF EXISTS DBO.ACCOUNT;
GO

DROP TABLE IF EXISTS DBO.PROGRAM;

DROP TABLE IF EXISTS DBO.GROUPS;
GO